---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
st:
  secret-id:

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: example
spec:
  provider:
    vault:
      server: "http://172.31.33.80:8200"
      path: "roboshop-dev"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleId: "453baaaa-1408-29a6-68a0-75be6d1961f1"
          secretRef:
            name: "my-secret"
            key: "secret-id"