apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
  labels:
    app: my-app
  namespace: external-dns
spec:
  containers:
    - name: my-app-container
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service1
  annotations:
  labels:
    app: my-app
  namespace: external-dns
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing1
  namespace: external-dns
spec:
  ingressClassName: nginx
  rules:
    - host: "chaitu.azcart.online"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: service1
                port:
                  number: 80