apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: team-b-store
    kind: SecretStore
  target:
    name: example-sync
  dataFrom:
    - prefix: dev.*

---
apiVersion: externalsecrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: my-app-secrets
spec:
  secretStoreRef:
    name: team-b-store
    kind: SecretStore # Refers to the SecretStore resource (defined in the previous step)
  target:
    name: my-app-secret  # The name of the Kubernetes secret to be created
  dataFrom:
    - prefix: /dev.*/  # Pull all parameters under the path "/my-app/"
