apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: team-b-store
    kind: SecretStore
  target:
    name: example-sync
  data:
    - secretKey: dev_f
      remoteRef:
        key: dev.frontend

    - secretKey: prod_f
      remoteRef:
        key: prod.frontend

