apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: team-b-store
    kind: SecretStore
  target:
    name: example-sync
  data:
    - secretKey: tags
      remoteRef:
        metadataPolicy: Fetch
        key: dev
