apiVersion: v1
kind: Secret
metadata:
  name: secret-p
data:
  access-key: QUtJQVU2R0RZTUw3T1pXNkZYVUk=
  secret-access-key: R2w0VFNzSjhHRjdNeXI2TXlGeUIrNVgyT0JmOFlobEs3QWErams3MQ==



---

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: team-b-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      role: arn:aws:iam::339712959230:role/normal_role_params
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: secret-p
            key: access-key
          secretAccessKeySecretRef:
            name: secret-p
            key: secret-access-key

